name: RetiNotes
description: "Aravind E-Logbook Phase 1A (Auth MVP)"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  supabase_flutter: ^2.6.0
  google_sign_in: ^6.2.1
  async: ^2.11.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  csv: ^6.0.0
  share_plus: ^10.0.2
  path_provider: ^2.1.5
  pdf: ^3.11.1
  printing: ^5.14.1
  retry: ^3.1.2
  path: ^1.9.0
  file_picker: ^8.0.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fonts/NotoSans-Regular.ttf
    - assets/AppLaunch.gif

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_1.png"

flutter_native_splash:
  color: "#1565C0"
  image: assets/logo.png
  android: true
  ios: true
